# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f7123eb8f17575d1aae1768e15a02c886c76cd2881c028d81a761eb3da77826bc9bedf89b4defba93e7ee5039b528304db362b042d94305040b7cc85bcd3d0d

test:
  secret_key_base: df50671f29fc2335ea7283288a48d039c52bf32e598a8812776bec8102a682e5c66652c1e3c6a5cbbe74823e2afc66b00bb99ecf58c20f7e8af51d4fd3bfc892

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
